### ISSUE TITLE
Bug in date validation?

### ISSUE THREAD

**Issue by Foxcapades** [VEuPathDB/script-find-bin-width#4]
```
panic: runtime error: index out of range [20] with length 4

  goroutine 1 [running]:
  find-bin-width/pkg/xtype.validateTimestamp({0xc00023a2dc?, 0x4dae01?})
        /home/ellie/code/upenn/go/script/find-bin-width/pkg/xtype/detect-date.go:97 +0x111
  find-bin-width/pkg/xtype.valueIsDate({0xc00023a2dc?, 0x4e3413?})
        /home/ellie/code/upenn/go/script/find-bin-width/pkg/xtype/detect-date.go:29 +0x85
  find-bin-width/pkg/xtype.stateUndecided({0xc00023a2dc, 0x4})
        /home/ellie/code/upenn/go/script/find-bin-width/pkg/xtype/detect.go:33 +0x46
  find-bin-width/pkg/xtype.FindDataType({0xc00023a2dc?, 0x505ca0?}, 0xcb?)
        /home/ellie/code/upenn/go/script/find-bin-width/pkg/xtype/detect.go:22 +0x47
  find-bin-width/pkg/input.(*lineEntries).append(0xc000083c58, 0xc00023de00, {0xc00023a2dc, 0x4}, 0xc8?)
        /home/ellie/code/upenn/go/script/find-bin-width/pkg/input/line-entries.go:32 +0xb9
  find-bin-width/pkg/input.(*collectingLineGroupIterator).Next(0xc0000c80e0)
        /home/ellie/code/upenn/go/script/find-bin-width/pkg/input/group-iterator.go:98 +0x406
  find-bin-width/pkg/stats.(*ResultIterator).Next(0xc0000c80e0?)
        /home/ellie/code/upenn/go/script/find-bin-width/pkg/stats/result-iterator.go:16 +0x39
  main.processInput({0x548cd0?, 0xc00006e018?}, {0x549360, 0xc000002180}, 0x7f93841cd868?)
        /home/ellie/code/upenn/go/script/find-bin-width/bin/find-bin-width/main.go:62 +0x1a9
  main.main()
        /home/ellie/code/upenn/go/script/find-bin-width/bin/find-bin-width/main.go:28 +0xd6
```

**Comment by Foxcapades** [comment]
Resolved in v1.0.1
